services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - database

volumes:
  postgres:
